/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.monster.vista;


import ec.edu.monster.controlador.Localidad;
import ec.edu.monster.controlador.PartidoFutbol;
import ec.edu.monster.service.PartidoFutbolService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SebastianLG
 */
public class JFrame_Localidades extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_ConversionUnidades
     */
    public JFrame_Localidades() {
        initComponents();
        this.setLocationRelativeTo(null);
        
         //DATOS
        List<Localidad> localidades = new ArrayList<Localidad>();
        List<PartidoFutbol> partidoFutbol = new ArrayList<PartidoFutbol>();
        String codigosPartidos = "";
        int codigoPartido = 0;
        ArrayList<Integer> codigos = new ArrayList<>();
        for(PartidoFutbol p: partidoFutbol){
            codigosPartidos += "\n" + p.getCodigo() + " - " + p.getEquipoLocal() + " vs " + p.getEquipoVisita();
            codigos.add(p.getCodigo());
        }
        JOptionPane.showMessageDialog(null, "Escoja un código del partido para ver sus localidades");
        do{
            codigoPartido = Integer.parseInt(JOptionPane.showInputDialog(null, codigosPartidos));
        }while(!codigos.contains(codigoPartido));
        
        
        //PROCESO
        PartidoFutbolService partidoFutbolService = new PartidoFutbolService();
        localidades = partidoFutbolService.listarLocalidades(codigoPartido);
        
        
        //REPORTE
        DefaultTableModel model = new DefaultTableModel();
        
        for(Localidad l: localidades){
            model.addRow(new Object[]{l.getCodigoLocalidad(), l.getPartido(), l.getCodigoLocalidad(), l.getDisponibilidad(), l.getPrecio()});
        }
       
        table_localidades.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_localidades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ticket Premium");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Partidos de fútbol disponibles");

        table_localidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Partido", "Localidad", "Disponibilidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_localidades);
        if (table_localidades.getColumnModel().getColumnCount() > 0) {
            table_localidades.getColumnModel().getColumn(0).setResizable(false);
            table_localidades.getColumnModel().getColumn(1).setResizable(false);
            table_localidades.getColumnModel().getColumn(2).setResizable(false);
            table_localidades.getColumnModel().getColumn(3).setResizable(false);
            table_localidades.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Localidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_localidades;
    // End of variables declaration//GEN-END:variables
}
